version: '3'
services:
  app:
    build: app 
    container_name: app
    command: /bin/bash
    tty: true
  db:
    image: mysql:5.7
    container_name: db
    volumes:
      - db_data:/var/lib/mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: tutrial
      MYSQL_USER: root
      MYSQL_PASSWORD: password
  redis:
    image: "redis:latest"
    container_name: redis
    ports:
      - "6379:6379"
    volumes:
      - "./data/redis:/data" 
volumes:
   db_data:
 
