version: '3'
services:
  app:
    build: app 
    container_name: app
    command: /bin/bash
    tty: true
  db:
    image: mysql:5.7
    container_name: db
    volumes:
      - ./initdb.d:/docker-entrypoint-initdb.d
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: demo

  redis:
    image: "redis:latest"
    container_name: redis
    ports:
      - "6379:6379"
    volumes:
      - "./data/redis:/data" 
 
